# Generated by Django 3.2.8 on 2022-03-10 12:58

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MapGrid',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField()),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('right', models.FloatField()),
                ('bottom', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ForcingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('precipitation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None), blank=True, null=True, size=None)),
                ('tair', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acgmap.mapgrid', verbose_name='related grid cell')),
            ],
        ),
        migrations.CreateModel(
            name='CryoGridData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('lat', models.DecimalField(decimal_places=3, default=None, max_digits=6)),
                ('long', models.DecimalField(decimal_places=3, default=None, max_digits=6)),
                ('t_max_all', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None)),
                ('t_min_all', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None)),
                ('t_av_all', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='acgmap.mapgrid', verbose_name='related grid cell')),
            ],
        ),
    ]
