# Generated by Django 3.2.8 on 2022-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgmap', '0002_auto_20220310_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_level', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True)),
            ],
        ),
    ]
