# Generated by Django 3.2.8 on 2022-04-04 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgmap', '0003_depthlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryogriddata',
            old_name='t_av_all',
            new_name='t_av_all_101',
        ),
        migrations.RenameField(
            model_name='cryogriddata',
            old_name='t_max_all',
            new_name='t_av_all_51',
        ),
        migrations.RenameField(
            model_name='cryogriddata',
            old_name='t_min_all',
            new_name='t_av_all_rev',
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_all_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_all_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_all_rev',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_all_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_all_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_all_rev',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=9), size=None), default=None, size=None),
        ),
    ]
