# Generated by Django 3.2.8 on 2022-05-17 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acgmap', '0004_auto_20220404_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_historical_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_historical_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_iceage_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_iceage_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_preindustrial_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_av_preindustrial_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_historical_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_historical_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_iceage_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_iceage_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_preindustrial_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_max_preindustrial_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_historical_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_historical_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_iceage_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_iceage_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_preindustrial_101',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='t_min_preindustrial_51',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=9), default=[], size=None),
            preserve_default=False,
        ),
    ]
