# Generated by Django 3.2 on 2021-05-11 14:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForcingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('precipitation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None), size=None)),
                ('air_temperature', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('min_depth', models.PositiveBigIntegerField()),
                ('max_depth', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('min_depth', models.PositiveBigIntegerField()),
                ('max_depth', models.PositiveBigIntegerField()),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgmap.soiltype', verbose_name='related soil type')),
            ],
        ),
        migrations.CreateModel(
            name='CryoGridData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('forcing_data', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.forcingdata', verbose_name='related forcing data')),
                ('soil_characteristics', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.soilcharacteristics', verbose_name='related soil characteristics')),
            ],
        ),
    ]
