# Generated by Django 3.2 on 2021-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='long',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
    ]
