# Generated by Django 3.2 on 2021-05-12 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='TSOIL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=15, default=None, max_digits=18), size=None), default=None, size=None),
            preserve_default=False,
        ),
    ]
