# Generated by Django 3.2 on 2021-05-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0002_cryogriddata_tsoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryogriddata',
            old_name='TSOIL',
            new_name='tsoil',
        ),
    ]
