# Generated by Django 3.2 on 2021-04-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0002_auto_20210422_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='forcing_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.forcingdata', verbose_name='related forcing data'),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='soil_characteristics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.soilcharacteristics', verbose_name='related soil characteristics'),
        ),
    ]
