# Generated by Django 3.2 on 2021-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0004_cryogriddata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryogriddata',
            name='name',
        ),
        migrations.AlterField(
            model_name='forcingdata',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='soilcharacteristics',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.TextField(),
        ),
    ]
