# Generated by Django 3.2 on 2021-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0005_auto_20210512_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forcingdata',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soilcharacteristics',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
