# Generated by Django 3.2 on 2021-05-18 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0006_auto_20210517_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='alt',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='cryogriddata',
            name='z_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
