# Generated by Django 3.2 on 2021-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0007_auto_20210518_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcingdata',
            old_name='air_temperature',
            new_name='tair',
        ),
    ]
