# Generated by Django 3.2 on 2021-05-19 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0008_rename_air_temperature_forcingdata_tair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcingdata',
            name='tair',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=16, default=None, max_digits=19), size=None), size=None),
        ),
    ]
