# Generated by Django 3.2 on 2021-05-19 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0009_alter_forcingdata_tair'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None),
            preserve_default=False,
        ),
    ]
