# Generated by Django 3.2 on 2021-06-01 07:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0010_cryogriddata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('right', models.FloatField()),
                ('bottom', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='cryogriddata',
            name='tsoil',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=6), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='forcingdata',
            name='tair',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, default=None, max_digits=6), size=None), size=None),
        ),
    ]
