# Generated by Django 3.2 on 2021-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0011_auto_20210601_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapgrid',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
