# Generated by Django 3.2 on 2021-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0012_alter_mapgrid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapgrid',
            name='id',
        ),
        migrations.AddField(
            model_name='mapgrid',
            name='auto_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
