# Generated by Django 3.2 on 2021-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0013_auto_20210601_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgrid',
            name='id',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
