# Generated by Django 3.2 on 2021-06-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0014_mapgrid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryogriddata',
            name='grid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.mapgrid', verbose_name='related grid cell'),
        ),
        migrations.AddField(
            model_name='forcingdata',
            name='grid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cgmap.mapgrid', verbose_name='related grid cell'),
        ),
    ]
