# Generated by Django 3.2 on 2021-06-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0016_auto_20210621_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryogriddata',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='forcingdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forcingdata',
            name='start_date',
        ),
    ]
