# Generated by Django 3.2 on 2021-06-21 13:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0017_auto_20210621_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryogriddata',
            name='forcing_data',
        ),
        migrations.AlterField(
            model_name='cryogriddata',
            name='soil_characteristics',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgmap.soilcharacteristics', verbose_name='related soil characteristics'),
        ),
        migrations.AlterField(
            model_name='forcingdata',
            name='precipitation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None), blank=True, null=True, size=None),
        ),
    ]
