# Generated by Django 3.2 on 2021-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0019_auto_20210621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryogriddata',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
