# Generated by Django 3.2 on 2021-06-21 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0020_alter_cryogriddata_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryogriddata',
            name='z_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=None, null=True, size=None),
        ),
    ]
