# Generated by Django 3.2 on 2021-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0021_alter_cryogriddata_z_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryogriddata',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cryogriddata',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cryogriddata',
            name='long',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6),
        ),
    ]
