# Generated by Django 3.2 on 2021-06-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0023_auto_20210624_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='date',
            new_name='time',
        ),
    ]
