# Generated by Django 3.2 on 2021-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0026_temperaturedepthlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_level', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cryogriddata',
            name='z_level',
        ),
    ]
