# Generated by Django 3.2 on 2021-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0027_auto_20210906_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthlevel',
            name='z_level',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
    ]
