# Generated by Django 3.2.8 on 2022-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0028_auto_20210906_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryogriddata',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True),
        ),
    ]
