# Generated by Django 3.2.7 on 2021-09-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0028_auto_20210906_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryogriddata',
            name='time',
        ),
    ]
