# Generated by Django 3.2.7 on 2022-02-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0029_auto_20220216_1154'),
        ('cgmap', '0029_remove_cryogriddata_time'),
    ]

    operations = [
    ]
