# Generated by Django 3.2.8 on 2022-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0030_auto_20220302_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryogriddata',
            name='time',
        ),
    ]
