# Generated by Django 3.2.8 on 2022-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgmap', '0031_remove_cryogriddata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilcharacteristics',
            name='max_depth',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soilcharacteristics',
            name='min_depth',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='max_depth',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='min_depth',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
    ]
